local H = dofile(assert(os.getenv("HERDR_TEST_ROOT")) .. "/tests/helpers.lua")
local ha = require("herdr-ask")
H.project({ ["db.lua"] = { "l1", "l2", "l3", "l4", "l5" }, ["api.lua"] = { "a", "b", "c", "d" } })
ha.setup({ focus_after_send = false })
local cap = H.stub_transport(ha)
local A = require("herdr-ask.annotations")

H.annotate(ha, "db.lua", 2, 4, "leaks a connection")
H.annotate(ha, "api.lua", 3, 3, "await?\nblocks the pool")
H.annotate(ha, "db.lua", 1, 1, "unchecked nil")
H.eq(A.info().count, 3, "pending count")
H.ok(vim.fn.filereadable(A.info().path) == 1, "state file written")

A.send(false)
H.confirm_send(true)
H.ok(cap.args ~= nil, "prompt not sent")
local msg = cap.args[4]
H.eq(cap.args[1], "agent"); H.eq(cap.args[2], "prompt")
H.ok(msg:find("^Review these annotations%."), "instruction header")
H.ok(msg:find("## api%.lua") < msg:find("## db%.lua"), "files alphabetical")
H.ok(msg:find("@db%.lua#L2%-4 — leaks a connection"), "db L2-4 bullet")
H.ok(msg:find("@db%.lua#L1 — unchecked nil"), "db L1 bullet")
H.ok(msg:find("await%?\n  blocks the pool"), "multiline note indented")
H.ok(msg:find("L1 — unchecked nil") < msg:find("L2%-4 — leaks"), "lines sorted within file")
H.eq(A.info().count, 0, "cleared after send")
H.pass()
